---
title: "MCMC_results_notebook"
author: "Jeff Minucci"
date: "May 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if(Sys.info()[4]=="DZ2626UJMINUCCI"){
vpdir<-path.expand("d:/Git_files/minucci_vp_mcmc/")
vrp_filename <- "default_jeff.vrp"
}


#code sources and packages
library(coda)
library(fitR)
library(MCMCvis)
library(devtools)
install_github("quanted/VarroaPopWrapper",ref="master")
library(VarroaPopWrapper)



#load results
main_results <- readRDS(file=paste(vpdir,"output/mcmc_run_objects/run_5_11_18_p5.rds",sep = ""))
results <- mcmc(main_results$param_trace[, main_results$mcmc_params$optimize_vars[["names"]]])
results_bt <- burnAndThin(results,burn=50000,thin=1000)

```



```{r}
MCMCpstr(results_bt,median) #get median values


#get maximum likelihood parameter estimates
mle_pars <- main_results$param_trace[which(main_results$like_trace == max(main_results$like_trace)),][1,]
#mle_pars <- mle_pars[names(mle_pars) != "sd"]


#run sim with the mle
source(paste(vpdir,"src/misc/run_one.R",sep = "")) 
vrp_file <- paste(vpdir,'bin/',vrp_filename,sep="")
mle_output <- run_one(mle_pars, vrp_file = vrp_file,save_files=T)

#example plot - first site
mle_site1 <- mle_output[[1]]
plot(1:length(mle_site1[,4]),(mle_site1[,4]+mle_site1[,5]),type='b')


#get 95% c.i. for AILarvaLD50
quantile(main_results$param_trace$AILarvaLD50[50000:length(main_results$like_trace)], c(.025,.975))

```

```{r}
###calculate 95% confidence intervals around predictions, using our mcmc samples

#take 10k random samples of our mcmc data (leaving out first 50k burn-in)
#samples <- sample(50001:length(main_results$like_trace),10000,replace=F)
#mcmc_bootstrap <- main_results$prop_out_trace[samples,]

#convert proposal output trace to the steps actual output (stationary distribution)
lagged_like <- c(999, main_results$like_trace[-length(main_results$like_trace)])
rejects <- lagged_like == c(main_results$like_trace)
predictions <- array(NA, dim=dim(main_results$prop_out_trace))
for(i in 1:length(main_results$like_trace)){
  if(!rejects[i]){
    last_accept <-  main_results$prop_out_trace[,,i]
  }
  predictions[,,i] <- last_accept
}

#example: get 5 and 95% CI for all sites and dates
low_ci <- matrix(rep(NA),ncol=3,nrow=10)
high_ci <- matrix(rep(NA),ncol=3,nrow=10)
for(i in 1:10){
  for(j in 1:3){
    cis <- quantile(predictions[i,j,50000:300000], c(.025,.9725))
    low_ci[i,j] <- cis[1]
    high_ci[i,j] <- cis[2]
  }
}

```

```{r}
###Plot mle fit to data


vp_field_data <- paste(vpdir,"data/raw/field_bee_areas.csv",sep="")
field_data <- read.csv(vp_field_data)
bees_per_cm2 <- 1.45  #convert area of bees to individuals  
bee_pops <- as.matrix(field_data[,c("bees_cm2_5","bees_cm2_6","bees_cm2_8")]) * bees_per_cm2 
bee_initial <- round(field_data[,c("bees_cm2_4")] * bees_per_cm2,0)
bee_pops <- cbind(bee_initial,bee_pops)

#fitted mle
fitted <- main_results$prop_out_trace[,,which(main_results$like_trace == max(main_results$like_trace))[1]]
fitted <- cbind(bee_initial,fitted)
fitted

#sd
sd_mle <- main_results$param_trac[which(main_results$like_trace == max(main_results$like_trace))[1],"sd"][1]

#mean and peak clo concentrations
clo_summary <- read.csv(paste(vpdir,'data/processed/field_neonic_means_peaks.csv',sep=""))
clo_summary$Mean <- round(clo_summary$Mean,1)
clo_summary$Peak <- round(clo_summary$Peak,1)


#standard error for field data
std.err <- function(x){sd(x)/sqrt(length(x))}
hive_data <- read.csv(paste(vpdir,'data/raw/field_bee_areas_hive.csv', sep=""))
cm2_to_bees <- 1.45 #FROM 02write_input.R (via field tests)
hive_data$bees <- hive_data$bees_cm2 * cm2_to_bees
hive_data$month <- factor(hive_data$month)
SE <- aggregate(bees ~ site_abv + month, data=hive_data,std.err)
SE



pdf(paste(vpdir,"/reports/figures/mle_pop_fitted_ci_label_v2.pdf",sep=""),w=8,h=14)
par(mfrow=c(5,2))
for(i in 1:10){
  plot(c(4,5,6,8),bee_pops[i,]/1000,type='p', pch=19,ylim=c(0,45),xlab="Month of year",ylab="# of bees (1000s)")
  lines(c(4,5,6,8),fitted[i,]/1000,col='darkgrey',lwd=2)
  #lines(c(4,5,6,8),(fitted[i,]+sd_mle)/1000,col='darkgrey',lwd=2,lty=2)
  #lines(c(4,5,6,8),(fitted[i,]-sd_mle)/1000,col='darkgrey',lwd=2,lty=2)
  
  #bootstrapped 95% CI
  lines(c(4,5,6,8),(cbind(bee_initial,low_ci)[i,])/1000,col='darkgrey',lwd=2,lty=2)
  lines(c(4,5,6,8),(cbind(bee_initial,high_ci)[i,])/1000,col='darkgrey',lwd=2,lty=2)
  
  #standard error for field pop estimates
  
  arrows(c(4,5,6,8),(bee_pops[i,]+SE[c(i,i+10,i+20,i+30),3])/1000, c(4,5,6,8), (bee_pops[i,]-SE[c(i,i+10,i+20,i+30),3])/1000,
  length=0.05, angle=90, code=3)
  
  #text annotation
  text(c(6.5,6.5,6.5),c(44,39,34), c(paste('Site:',clo_summary[i,1]),paste('Mean clo.:',clo_summary[i,2], 'ppb'), 
                               paste('Peak clo.:', clo_summary[i,3],'ppb')),pos=4)
}
dev.off()



#just first 4 sites for iEMSs presentation
per_corn <- c(22,1,49,30,22,19,39,8,31,30)
pdf(paste(vpdir,"/reports/figures/field_pops_first4_v2.pdf",sep=""),w=8,h=7)
par(mfrow=c(2,2))
for(i in 1:4){
  plot(c(4,5,6,8),bee_pops[i,]/1000,type='n', pch=19,ylim=c(0,45),xlab="Month of year",ylab="# of bees (1000s)",lwd=2)
  rect(4,-10,4.3,80,col="cornflowerblue")
  points(c(4,5,6,8),bee_pops[i,]/1000, pch=19)
  lines(c(4,5,6,8),bee_pops[i,]/1000,lwd=2)
  
  arrows(c(4,5,6,8),(bee_pops[i,]+SE[c(i,i+10,i+20,i+30),3])/1000, c(4,5,6,8), (bee_pops[i,]-SE[c(i,i+10,i+20,i+30),3])/1000,
  length=0.05, angle=90, code=3)
  
  #text annotation
  text(c(6.1,6.1),c(44,39), c(paste('Site:',clo_summary[i,1]),paste('Corn cover: ',per_corn[i],'%',sep="")),pos=4)
}
dev.off()

```


